version: "3.9"
services:
  atcampus-db:
    container_name: 'atcampus-db'
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  atcampus-app:
    container_name: 'atcampus-app'
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - atcampus-db
    ports:
      - '3000:3000'