on:
  push:
    branches:
      - main
jobs:
  verify:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          github-token: ${{ secrets.SECRET_TOKEN }}
      - name: install dependencies
        run: npm install
      - run: npm test
      - name: Collect coverage for server
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: server
